### ISSUE TITLE
Created online version

### ISSUE THREAD

**Issue by JimmyDansbo** [joolin1/x16-PiskelC2Binary#3]
Using this repository and source code for the piskelc2bin.exe program, I have created an online version that can be found here: https://cx16.dk/piskelc2bin/
Let me know if this is is not ok with you.

**Comment by joolin1** [comment]
No problem at all. But I have made a another better converter now. It converts png-files to binary files. I will add that to github as soon as possible.

**Comment by JimmyDansbo** [comment]
I might just "steal" that as well, if that is OK ?

**Comment by joolin1** [comment]
Now I have created a new repository with the other converter: https://github.com/joolin1/x16-Png2Binary. Feel free to use in anyway you want. It is simple, it is limited. But well, we are a bunch of people enjoying coding for the CommanderX16 and maybe it can be of some help.

**Comment by JimmyDansbo** [comment]
Looks great. When I have the time, I will look into creating an online version.
I am really looking forward to seeing your CX16 code. You were doing a racing game, right?
